[package]
name = "finances-v2"
version = "0.1.0"
description = "Personal finances management app"
authors = ["V3P"]
edition = "2021"

[lib]
name = "finances_v2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
