export type CurrencyType = "fiat" | "crypto";

export interface Currency {
  code: string;
  name: string;
  symbol: string;
  flagCode: string;
  type: CurrencyType;
}

// Ported from tmp_currencies.dart. Insertion order preserved so major currencies stay at the top.
export const CURRENCIES: Record<string, Currency> = {
  // Fiat
  USD: { code: "USD", name: "US Dollar", symbol: "$", flagCode: "US", type: "fiat" },
  EUR: { code: "EUR", name: "Euro", symbol: "€", flagCode: "EU", type: "fiat" },
  GBP: { code: "GBP", name: "British Pound", symbol: "£", flagCode: "GB", type: "fiat" },
  JPY: { code: "JPY", name: "Japanese Yen", symbol: "¥", flagCode: "JP", type: "fiat" },
  CNY: { code: "CNY", name: "Chinese Yuan", symbol: "¥", flagCode: "CN", type: "fiat" },
  AUD: { code: "AUD", name: "Australian Dollar", symbol: "$", flagCode: "AU", type: "fiat" },
  CAD: { code: "CAD", name: "Canadian Dollar", symbol: "$", flagCode: "CA", type: "fiat" },
  CHF: { code: "CHF", name: "Swiss Franc", symbol: "CHF", flagCode: "CH", type: "fiat" },
  HKD: { code: "HKD", name: "Hong Kong Dollar", symbol: "$", flagCode: "HK", type: "fiat" },
  SGD: { code: "SGD", name: "Singapore Dollar", symbol: "$", flagCode: "SG", type: "fiat" },
  SEK: { code: "SEK", name: "Swedish Krona", symbol: "kr", flagCode: "SE", type: "fiat" },
  KRW: { code: "KRW", name: "South Korean Won", symbol: "₩", flagCode: "KR", type: "fiat" },
  NOK: { code: "NOK", name: "Norwegian Krone", symbol: "kr", flagCode: "NO", type: "fiat" },
  NZD: { code: "NZD", name: "New Zealand Dollar", symbol: "$", flagCode: "NZ", type: "fiat" },
  INR: { code: "INR", name: "Indian Rupee", symbol: "₹", flagCode: "IN", type: "fiat" },
  MXN: { code: "MXN", name: "Mexican Peso", symbol: "$", flagCode: "MX", type: "fiat" },
  TWD: { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", flagCode: "TW", type: "fiat" },
  ZAR: { code: "ZAR", name: "South African Rand", symbol: "R", flagCode: "ZA", type: "fiat" },
  BRL: { code: "BRL", name: "Brazilian Real", symbol: "R$", flagCode: "BR", type: "fiat" },
  DKK: { code: "DKK", name: "Danish Krone", symbol: "kr", flagCode: "DK", type: "fiat" },
  PLN: { code: "PLN", name: "Polish Złoty", symbol: "zł", flagCode: "PL", type: "fiat" },
  THB: { code: "THB", name: "Thai Baht", symbol: "฿", flagCode: "TH", type: "fiat" },
  IDR: { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flagCode: "ID", type: "fiat" },
  HUF: { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flagCode: "HU", type: "fiat" },
  CZK: { code: "CZK", name: "Czech Koruna", symbol: "Kč", flagCode: "CZ", type: "fiat" },
  ILS: { code: "ILS", name: "Israeli New Shekel", symbol: "₪", flagCode: "IL", type: "fiat" },
  CLP: { code: "CLP", name: "Chilean Peso", symbol: "$", flagCode: "CL", type: "fiat" },
  PHP: { code: "PHP", name: "Philippine Peso", symbol: "₱", flagCode: "PH", type: "fiat" },
  AED: { code: "AED", name: "UAE Dirham", symbol: "د.إ", flagCode: "AE", type: "fiat" },
  COP: { code: "COP", name: "Colombian Peso", symbol: "$", flagCode: "CO", type: "fiat" },
  SAR: { code: "SAR", name: "Saudi Riyal", symbol: "﷼", flagCode: "SA", type: "fiat" },
  MYR: { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flagCode: "MY", type: "fiat" },
  RON: { code: "RON", name: "Romanian Leu", symbol: "lei", flagCode: "RO", type: "fiat" },
  RUB: { code: "RUB", name: "Russian Ruble", symbol: "₽", flagCode: "RU", type: "fiat" },
  VND: { code: "VND", name: "Vietnamese Đồng", symbol: "₫", flagCode: "VN", type: "fiat" },
  AFN: { code: "AFN", name: "Afghan Afghani", symbol: "؋", flagCode: "AF", type: "fiat" },
  ALL: { code: "ALL", name: "Albanian Lek", symbol: "L", flagCode: "AL", type: "fiat" },
  DZD: { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flagCode: "DZ", type: "fiat" },
  AOA: { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flagCode: "AO", type: "fiat" },
  ARS: { code: "ARS", name: "Argentine Peso", symbol: "$", flagCode: "AR", type: "fiat" },
  AMD: { code: "AMD", name: "Armenian Dram", symbol: "֏", flagCode: "AM", type: "fiat" },
  AZN: { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flagCode: "AZ", type: "fiat" },
  BHD: { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flagCode: "BH", type: "fiat" },
  BDT: { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flagCode: "BD", type: "fiat" },
  BBD: { code: "BBD", name: "Barbadian Dollar", symbol: "$", flagCode: "BB", type: "fiat" },
  BYN: { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flagCode: "BY", type: "fiat" },
  BZD: { code: "BZD", name: "Belize Dollar", symbol: "$", flagCode: "BZ", type: "fiat" },
  BMD: { code: "BMD", name: "Bermudian Dollar", symbol: "$", flagCode: "BM", type: "fiat" },
  BOB: { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", flagCode: "BO", type: "fiat" },
  BAM: { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", flagCode: "BA", type: "fiat" },
  BWP: { code: "BWP", name: "Botswana Pula", symbol: "P", flagCode: "BW", type: "fiat" },
  BND: { code: "BND", name: "Brunei Dollar", symbol: "$", flagCode: "BN", type: "fiat" },
  BGN: { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flagCode: "BG", type: "fiat" },
  BIF: { code: "BIF", name: "Burundian Franc", symbol: "Fr", flagCode: "BI", type: "fiat" },
  KHR: { code: "KHR", name: "Cambodian Riel", symbol: "៛", flagCode: "KH", type: "fiat" },
  CVE: { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", flagCode: "CV", type: "fiat" },
  KYD: { code: "KYD", name: "Cayman Islands Dollar", symbol: "$", flagCode: "KY", type: "fiat" },
  XAF: { code: "XAF", name: "Central African CFA Franc", symbol: "Fr", flagCode: "CM", type: "fiat" },
  XOF: { code: "XOF", name: "West African CFA Franc", symbol: "Fr", flagCode: "SN", type: "fiat" },
  XPF: { code: "XPF", name: "CFP Franc", symbol: "Fr", flagCode: "PF", type: "fiat" },
  KMF: { code: "KMF", name: "Comorian Franc", symbol: "Fr", flagCode: "KM", type: "fiat" },
  CDF: { code: "CDF", name: "Congolese Franc", symbol: "Fr", flagCode: "CD", type: "fiat" },
  CRC: { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flagCode: "CR", type: "fiat" },
  CUP: { code: "CUP", name: "Cuban Peso", symbol: "$", flagCode: "CU", type: "fiat" },
  DJF: { code: "DJF", name: "Djiboutian Franc", symbol: "Fr", flagCode: "DJ", type: "fiat" },
  DOP: { code: "DOP", name: "Dominican Peso", symbol: "RD$", flagCode: "DO", type: "fiat" },
  XCD: { code: "XCD", name: "East Caribbean Dollar", symbol: "$", flagCode: "AG", type: "fiat" },
  EGP: { code: "EGP", name: "Egyptian Pound", symbol: "£", flagCode: "EG", type: "fiat" },
  ETB: { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flagCode: "ET", type: "fiat" },
  FJD: { code: "FJD", name: "Fijian Dollar", symbol: "$", flagCode: "FJ", type: "fiat" },
  GMD: { code: "GMD", name: "Gambian Dalasi", symbol: "D", flagCode: "GM", type: "fiat" },
  GEL: { code: "GEL", name: "Georgian Lari", symbol: "₾", flagCode: "GE", type: "fiat" },
  GHS: { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flagCode: "GH", type: "fiat" },
  GTQ: { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flagCode: "GT", type: "fiat" },
  GNF: { code: "GNF", name: "Guinean Franc", symbol: "Fr", flagCode: "GN", type: "fiat" },
  GYD: { code: "GYD", name: "Guyanese Dollar", symbol: "$", flagCode: "GY", type: "fiat" },
  HTG: { code: "HTG", name: "Haitian Gourde", symbol: "G", flagCode: "HT", type: "fiat" },
  HNL: { code: "HNL", name: "Honduran Lempira", symbol: "L", flagCode: "HN", type: "fiat" },
  ISK: { code: "ISK", name: "Icelandic Króna", symbol: "kr", flagCode: "IS", type: "fiat" },
  IRR: { code: "IRR", name: "Iranian Rial", symbol: "﷼", flagCode: "IR", type: "fiat" },
  IQD: { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flagCode: "IQ", type: "fiat" },
  JMD: { code: "JMD", name: "Jamaican Dollar", symbol: "$", flagCode: "JM", type: "fiat" },
  JOD: { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flagCode: "JO", type: "fiat" },
  KZT: { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flagCode: "KZ", type: "fiat" },
  KES: { code: "KES", name: "Kenyan Shilling", symbol: "Sh", flagCode: "KE", type: "fiat" },
  KWD: { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flagCode: "KW", type: "fiat" },
  KGS: { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", flagCode: "KG", type: "fiat" },
  LAK: { code: "LAK", name: "Lao Kip", symbol: "₭", flagCode: "LA", type: "fiat" },
  LBP: { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flagCode: "LB", type: "fiat" },
  LSL: { code: "LSL", name: "Lesotho Loti", symbol: "L", flagCode: "LS", type: "fiat" },
  LRD: { code: "LRD", name: "Liberian Dollar", symbol: "$", flagCode: "LR", type: "fiat" },
  LYD: { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", flagCode: "LY", type: "fiat" },
  MOP: { code: "MOP", name: "Macanese Pataca", symbol: "P", flagCode: "MO", type: "fiat" },
  MKD: { code: "MKD", name: "Macedonian Denar", symbol: "ден", flagCode: "MK", type: "fiat" },
  MGA: { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", flagCode: "MG", type: "fiat" },
  MWK: { code: "MWK", name: "Malawian Kwacha", symbol: "MK", flagCode: "MW", type: "fiat" },
  MVR: { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", flagCode: "MV", type: "fiat" },
  MRU: { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", flagCode: "MR", type: "fiat" },
  MUR: { code: "MUR", name: "Mauritian Rupee", symbol: "₨", flagCode: "MU", type: "fiat" },
  MDL: { code: "MDL", name: "Moldovan Leu", symbol: "L", flagCode: "MD", type: "fiat" },
  MNT: { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", flagCode: "MN", type: "fiat" },
  MAD: { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flagCode: "MA", type: "fiat" },
  MZN: { code: "MZN", name: "Mozambican Metical", symbol: "MT", flagCode: "MZ", type: "fiat" },
  MMK: { code: "MMK", name: "Myanmar Kyat", symbol: "Ks", flagCode: "MM", type: "fiat" },
  NAD: { code: "NAD", name: "Namibian Dollar", symbol: "$", flagCode: "NA", type: "fiat" },
  NPR: { code: "NPR", name: "Nepalese Rupee", symbol: "₨", flagCode: "NP", type: "fiat" },
  ANG: { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", flagCode: "CW", type: "fiat" },
  NIO: { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", flagCode: "NI", type: "fiat" },
  NGN: { code: "NGN", name: "Nigerian Naira", symbol: "₦", flagCode: "NG", type: "fiat" },
  KPW: { code: "KPW", name: "North Korean Won", symbol: "₩", flagCode: "KP", type: "fiat" },
  OMR: { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", flagCode: "OM", type: "fiat" },
  PKR: { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flagCode: "PK", type: "fiat" },
  PAB: { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flagCode: "PA", type: "fiat" },
  PGK: { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", flagCode: "PG", type: "fiat" },
  PYG: { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", flagCode: "PY", type: "fiat" },
  PEN: { code: "PEN", name: "Peruvian Sol", symbol: "S/", flagCode: "PE", type: "fiat" },
  QAR: { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", flagCode: "QA", type: "fiat" },
  RWF: { code: "RWF", name: "Rwandan Franc", symbol: "Fr", flagCode: "RW", type: "fiat" },
  WST: { code: "WST", name: "Samoan Tālā", symbol: "T", flagCode: "WS", type: "fiat" },
  STN: { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", flagCode: "ST", type: "fiat" },
  RSD: { code: "RSD", name: "Serbian Dinar", symbol: "дин", flagCode: "RS", type: "fiat" },
  SCR: { code: "SCR", name: "Seychellois Rupee", symbol: "₨", flagCode: "SC", type: "fiat" },
  SLE: { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", flagCode: "SL", type: "fiat" },
  SBD: { code: "SBD", name: "Solomon Islands Dollar", symbol: "$", flagCode: "SB", type: "fiat" },
  SOS: { code: "SOS", name: "Somali Shilling", symbol: "Sh", flagCode: "SO", type: "fiat" },
  SSP: { code: "SSP", name: "South Sudanese Pound", symbol: "£", flagCode: "SS", type: "fiat" },
  LKR: { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", flagCode: "LK", type: "fiat" },
  SDG: { code: "SDG", name: "Sudanese Pound", symbol: "£", flagCode: "SD", type: "fiat" },
  SRD: { code: "SRD", name: "Surinamese Dollar", symbol: "$", flagCode: "SR", type: "fiat" },
  SZL: { code: "SZL", name: "Swazi Lilangeni", symbol: "L", flagCode: "SZ", type: "fiat" },
  SYP: { code: "SYP", name: "Syrian Pound", symbol: "£", flagCode: "SY", type: "fiat" },
  TJS: { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flagCode: "TJ", type: "fiat" },
  TZS: { code: "TZS", name: "Tanzanian Shilling", symbol: "Sh", flagCode: "TZ", type: "fiat" },
  TOP: { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", flagCode: "TO", type: "fiat" },
  TTD: { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$", flagCode: "TT", type: "fiat" },
  TND: { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", flagCode: "TN", type: "fiat" },
  TRY: { code: "TRY", name: "Turkish Lira", symbol: "₺", flagCode: "TR", type: "fiat" },
  TMT: { code: "TMT", name: "Turkmenistan Manat", symbol: "m", flagCode: "TM", type: "fiat" },
  UGX: { code: "UGX", name: "Ugandan Shilling", symbol: "Sh", flagCode: "UG", type: "fiat" },
  UAH: { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flagCode: "UA", type: "fiat" },
  UYU: { code: "UYU", name: "Uruguayan Peso", symbol: "$", flagCode: "UY", type: "fiat" },
  UZS: { code: "UZS", name: "Uzbekistani Soʻm", symbol: "soʻm", flagCode: "UZ", type: "fiat" },
  VUV: { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", flagCode: "VU", type: "fiat" },
  VES: { code: "VES", name: "Venezuelan Bolívar Soberano", symbol: "Bs.", flagCode: "VE", type: "fiat" },
  YER: { code: "YER", name: "Yemeni Rial", symbol: "﷼", flagCode: "YE", type: "fiat" },
  ZMW: { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flagCode: "ZM", type: "fiat" },
  ZWL: { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$", flagCode: "ZW", type: "fiat" },

  // Crypto
  BTC: { code: "BTC", name: "Bitcoin", symbol: "₿", flagCode: "BTC", type: "crypto" },
  ETH: { code: "ETH", name: "Ethereum", symbol: "Ξ", flagCode: "ETH", type: "crypto" },
  USDT: { code: "USDT", name: "Tether", symbol: "₮", flagCode: "USDT", type: "crypto" },
};

export const CURRENCY_LIST: Currency[] = Object.values(CURRENCIES);

export const FIAT_CURRENCIES: Currency[] = CURRENCY_LIST.filter(
  (c) => c.type === "fiat",
);

export const CRYPTO_CURRENCIES: Currency[] = CURRENCY_LIST.filter(
  (c) => c.type === "crypto",
);
