-- Currency dictionary, sourced from https://api.frankfurter.dev/v2/currencies on 2026-05-05.
-- `rate_source` is a free-form label of where conversion rates for this currency are pulled
-- from. Currently only one source ('frankfurter'); future extensions might add 'cbr',
-- 'binance', etc. NULL means "no automatic rate feed wired up for this currency".
CREATE TABLE currencies (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    symbol      TEXT NOT NULL,
    rate_source TEXT
);

INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AED', 'United Arab Emirates Dirham', 'د.إ', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AFN', 'Afghan Afghani', '؋', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ALL', 'Albanian Lek', 'L', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AMD', 'Armenian Dram', '֏', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ANG', 'Netherlands Antillean Gulden', 'ƒ', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AOA', 'Angolan Kwanza', 'Kz', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ARS', 'Argentine Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AUD', 'Australian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AWG', 'Aruban Florin', 'ƒ', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('AZN', 'Azerbaijani Manat', '₼', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'КМ', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BBD', 'Barbadian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BDT', 'Bangladeshi Taka', '৳', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BGN', 'Bulgarian Lev', 'лв.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BHD', 'Bahraini Dinar', 'د.ب', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BIF', 'Burundian Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BMD', 'Bermudian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BND', 'Brunei Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BOB', 'Bolivian Boliviano', 'Bs.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BRL', 'Brazilian Real', 'R$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BSD', 'Bahamian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BTN', 'Bhutanese Ngultrum', 'Nu.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BWP', 'Botswana Pula', 'P', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BYN', 'Belarusian Ruble', 'Br', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('BZD', 'Belize Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CAD', 'Canadian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CDF', 'Congolese Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CHF', 'Swiss Franc', 'CHF', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CLP', 'Chilean Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CNH', 'Chinese Renminbi Yuan Offshore', '¥', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CNY', 'Chinese Renminbi Yuan', '¥', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('COP', 'Colombian Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CRC', 'Costa Rican Colón', '₡', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CUP', 'Cuban Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CVE', 'Cape Verdean Escudo', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('CZK', 'Czech Koruna', 'Kč', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('DJF', 'Djiboutian Franc', 'Fdj', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('DKK', 'Danish Krone', 'kr.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('DOP', 'Dominican Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('DZD', 'Algerian Dinar', 'د.ج', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('EGP', 'Egyptian Pound', 'ج.م', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ERN', 'Eritrean Nakfa', 'Nfk', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ETB', 'Ethiopian Birr', 'Br', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('EUR', 'Euro', '€', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('FJD', 'Fijian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('FKP', 'Falkland Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GBP', 'British Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GEL', 'Georgian Lari', '₾', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GGP', 'Guernsey Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GHS', 'Ghanaian Cedi', '₵', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GIP', 'Gibraltar Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GMD', 'Gambian Dalasi', 'D', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GNF', 'Guinean Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GTQ', 'Guatemalan Quetzal', 'Q', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('GYD', 'Guyanese Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('HKD', 'Hong Kong Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('HNL', 'Honduran Lempira', 'L', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('HTG', 'Haitian Gourde', 'G', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('HUF', 'Hungarian Forint', 'Ft', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('IDR', 'Indonesian Rupiah', 'Rp', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ILS', 'Israeli New Shekel', '₪', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('IMP', 'Isle of Man Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('INR', 'Indian Rupee', '₹', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('IQD', 'Iraqi Dinar', 'ع.د', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('IRR', 'Iranian Rial', '﷼', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ISK', 'Icelandic Króna', 'kr.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('JEP', 'Jersey Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('JMD', 'Jamaican Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('JOD', 'Jordanian Dinar', 'د.ا', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('JPY', 'Japanese Yen', '¥', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KES', 'Kenyan Shilling', 'KSh', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KGS', 'Kyrgyzstani Som', 'som', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KHR', 'Cambodian Riel', '៛', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KMF', 'Comorian Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KRW', 'South Korean Won', '₩', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KWD', 'Kuwaiti Dinar', 'د.ك', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KYD', 'Cayman Islands Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('KZT', 'Kazakhstani Tenge', '₸', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LAK', 'Lao Kip', '₭', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LBP', 'Lebanese Pound', 'ل.ل', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LKR', 'Sri Lankan Rupee', '₨', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LRD', 'Liberian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LSL', 'Lesotho Loti', 'L', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('LYD', 'Libyan Dinar', 'ل.د', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MAD', 'Moroccan Dirham', 'د.م.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MDL', 'Moldovan Leu', 'L', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MGA', 'Malagasy Ariary', 'Ar', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MKD', 'Macedonian Denar', 'ден', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MMK', 'Myanmar Kyat', 'K', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MNT', 'Mongolian Tögrög', '₮', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MOP', 'Macanese Pataca', 'P', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MRO', 'Mauritanian Ouguiya', 'UM', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MRU', 'Mauritanian Ouguiya', 'UM', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MUR', 'Mauritian Rupee', '₨', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MVR', 'Maldivian Rufiyaa', 'MVR', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MWK', 'Malawian Kwacha', 'MK', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MXN', 'Mexican Peso', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MYR', 'Malaysian Ringgit', 'RM', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('MZN', 'Mozambican Metical', 'MTn', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NAD', 'Namibian Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NGN', 'Nigerian Naira', '₦', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NIO', 'Nicaraguan Córdoba', 'C$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NOK', 'Norwegian Krone', 'kr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NPR', 'Nepalese Rupee', 'Rs.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('NZD', 'New Zealand Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('OMR', 'Omani Rial', 'ر.ع.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PAB', 'Panamanian Balboa', 'B/.', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PEN', 'Peruvian Sol', 'S/', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PGK', 'Papua New Guinean Kina', 'K', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PHP', 'Philippine Peso', '₱', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PKR', 'Pakistani Rupee', '₨', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PLN', 'Polish Złoty', 'zł', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('PYG', 'Paraguayan Guaraní', '₲', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('QAR', 'Qatari Riyal', 'ر.ق', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('RON', 'Romanian Leu', 'Lei', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('RSD', 'Serbian Dinar', 'RSD', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('RUB', 'Russian Ruble', '₽', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('RWF', 'Rwandan Franc', 'FRw', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SAR', 'Saudi Riyal', 'ر.س', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SBD', 'Solomon Islands Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SCR', 'Seychellois Rupee', '₨', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SDG', 'Sudanese Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SEK', 'Swedish Krona', 'kr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SGD', 'Singapore Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SHP', 'Saint Helenian Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SLE', 'New Leone', 'Le', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SOS', 'Somali Shilling', 'Sh', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SRD', 'Surinamese Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SSP', 'South Sudanese Pound', '£', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('STN', 'São Tomé and Príncipe Second Dobra', 'Db', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SVC', 'Salvadoran Colón', '₡', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SYP', 'Syrian Pound', '£S', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('SZL', 'Swazi Lilangeni', 'E', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('THB', 'Thai Baht', '฿', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TJS', 'Tajikistani Somoni', 'ЅМ', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TMT', 'Turkmenistani Manat', 'm', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TND', 'Tunisian Dinar', 'د.ت', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TOP', 'Tongan Paʻanga', 'T$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TRY', 'Turkish Lira', '₺', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TTD', 'Trinidad and Tobago Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TWD', 'New Taiwan Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('TZS', 'Tanzanian Shilling', 'Sh', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('UAH', 'Ukrainian Hryvnia', '₴', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('UGX', 'Ugandan Shilling', 'USh', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('USD', 'United States Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('UYU', 'Uruguayan Peso', '$U', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('UZS', 'Uzbekistan Som', 'so''m', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('VES', 'Venezuelan Bolívar Soberano', 'Bs', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('VND', 'Vietnamese Đồng', '₫', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('VUV', 'Vanuatu Vatu', 'Vt', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('WST', 'Samoan Tala', 'T', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XAF', 'Central African CFA Franc', 'CFA', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XAG', 'Silver (Troy Ounce)', 'oz t', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XAU', 'Gold (Troy Ounce)', 'oz t', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XCD', 'East Caribbean Dollar', '$', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XCG', 'Caribbean Guilder', 'Cg', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XDR', 'Special Drawing Rights', 'SDR', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XOF', 'West African CFA Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XPD', 'Palladium', 'oz t', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XPF', 'CFP Franc', 'Fr', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('XPT', 'Platinum', 'oz t', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('YER', 'Yemeni Rial', '﷼', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ZAR', 'South African Rand', 'R', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ZMW', 'Zambian Kwacha', 'K', 'frankfurter');
INSERT INTO currencies (code, name, symbol, rate_source) VALUES ('ZWG', 'Zimbabwe Gold', 'ZiG', 'frankfurter');
